#!/bin/bash

cat > globals.html << 'EOF'
<html>
<head>
<title>Global variables</title>
  
<style type="text/css">
/* without the explicit `span`, this does not work in Ff3 (but in Safari) */
span.global:hover {
  text-decoration: underline;
  color: blue;
  cursor: pointer;
}
</style>

<script type="text/javascript"
  src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js">
</script>
<script type="text/javascript">
$(document).ready(function() {
  $('.uses').hide();
  $('.global').click(function() {
    $(this).next().slideToggle();
  });
});
</script>
</head>
<body>
EOF

make CC=../../../clangtut/tut08 | tee -a globals.html

cat >> globals.html << EOF
</body>
</html>
EOF
